import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { CategoryProvider } from "./components/CategoryProvider";

const inter = Poppins({
  subsets: ["latin", "latin-ext"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <CategoryProvider>
      <html lang="en" className="no-scrollbar">
        <body className={inter.className}>{children}</body>
      </html>
    </CategoryProvider>
  );
}
